name: Delete old workflow runs
on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: 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
          repository: flutterproject
          retain_days: 30
          keep_minimum_runs: 6
