name : CI/CD
on: push

jobs:
  Deploy:
    runs-on: windows-latest
    name: Deploy apk on nexus repository
    steps:
      - uses: actions/checkout@v3
      - name: Run test.sh script
        run: ./test.sh
        shell: bash
