name: Build and Deploy APKs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 2.x
        
    - name: Install dependencies and generate code
      run: |
        flutter pub get
        melos exec -- flutter pub run build_runner build --delete-conflicting-outputs
        
    - name: Build APKs
      run: flutter build apk --release
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
